version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 9063770754
      POSTGRES_DB: meeting_scheduler_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  scheduler:
    image: scheduler:latest
    container_name: scheduler_service
    restart: always
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: 9063770754
      DB_NAME: meeting_scheduler_db
    
    ports:
      - "8081:8081"

volumes:
  postgres_data:
