apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    {{- toYaml .Values.labels  | nindent 4 }}
data:
  POSTGRES_DB: {{ .Values.config.POSTGRES_DB}}
  POSTGRES_USER: {{ .Values.config.POSTGRES_USER}}
  POSTGRES_PASSWORD: {{ .Values.config.POSTGRES_PASSWORD}}
  PGDATA: {{ .Values.config.PGDATA}}