apiVersion: v1
kind: Service
metadata:
  name: vault-pgsql # Sets service name
  namespace: {{ .Release.Namespace }}
  labels:
    {{- toYaml .Values.labels  | nindent 4 }} # Labels and Selectors
spec:
  type: {{ .Values.service.type }} # Sets service type
  ports:
    - port: {{ .Values.service.port }} # Sets port to run the postgres application
      # nodePort: {{ .Values.service.nodePort }}
  selector:
    {{- toYaml .Values.labels  | nindent 4 }} 